### ISSUE TITLE
Add possibility in `opus list` to sort tasks

### ISSUE THREAD

**Issue by hlxid** [xNaCly/opusCli#16]
Currently, tasks are output in the order that they are inside the SQLite database.
It would be pretty handy to be able to sort the displayed tasks by priority, due date or id.
This could be done with a command line flag, e.g. `--sort priority` (maybe with short forms like `--sort prio`).

**Comment by xnacly** [comment]
Id say this change can only be done after #14 is finished, due to the complex way argument parsing is currently done. 

Will add this to the milestone for the next release.
